### ISSUE TITLE
Reclaimed account is showing can be reclaim.

### ISSUE THREAD

**Issue by anonimowy891** [Liskscan/lisk-explorer#15]
### Expected behavior
When paste legacy address to account analyzer, should return "status ok" or "can be reclaim".
If is reclaimed also should be visible new address.
### Actual behavior
Already reclaimed account is showing can be reclaim when paste legacy address to account analyzer.

https://liskscan.com/account/lskmb7jabaxhchxn3z9eveuc2hw4nda3s6np5hrgk
### Which version(s) does this affect? (Environment, OS, etc...)
MacBook Air -Safari 15.2
![Zrzut ekranu 2022-03-9 o 17 46 36](https://user-images.githubusercontent.com/63446761/157490344-919561c2-ba8b-45da-a056-e91ba2742e4f.png)
![Zrzut ekranu 2022-03-9 o 17 46 45](https://user-images.githubusercontent.com/63446761/157490357-099b3a42-270c-4bab-b30d-2b12de1ca2b4.png)

**Comment by corbifex** [comment]
fixed
