### ISSUE TITLE
Unknow account status using legacy address.

### ISSUE THREAD

**Issue by anonimowy891** [Liskscan/lisk-explorer#16]
### Expected behavior
When paste legacy address to account analyzer, which was initialized in old core, status should be "ok".
### Actual behavior
When paste legacy address to account analyzer, which was initialized in old core I get status "unknown".
When paste new "lsk" address to account analyzer, which was initialized in old core I get status "ok".
### Which version(s) does this affect? (Environment, OS, etc...)
MacBook Air - Safari 15.2
![Zrzut ekranu 2022-03-9 o 17 47 30](https://user-images.githubusercontent.com/63446761/157491601-83ca9724-efd3-456c-a58a-9cae2873ded8.png)
![Zrzut ekranu 2022-03-9 o 17 47 38](https://user-images.githubusercontent.com/63446761/157491611-d890be24-becf-4448-9f7e-e4ce6f93312a.png)
![Zrzut ekranu 2022-03-9 o 17 55 05](https://user-images.githubusercontent.com/63446761/157491620-cccc5646-d1d2-4060-ae1f-9887b3519ca7.png)

**Comment by corbifex** [comment]
> When paste legacy address to account analyzer, which was initialized in old core, status should be "ok".

The status is unknown because if I was attacked before the last mainnet upgrade there is no way to determine this so unknown until you enter a publicKey or new address. I will add a message for this.
