### ISSUE TITLE
Delegates page BigInt undefined

### ISSUE THREAD

**Issue by Baeliale** [Liskscan/lisk-explorer#21]
### Expected behavior
Load delegates page without errors

### Actual behavior
Loading delegates page sometimes gives a TypeError

![afbeelding](https://user-images.githubusercontent.com/94919546/160612322-18a350d4-3960-495b-99b6-5efbbcf88dc0.png)

### Steps to reproduce
Load delegates page on development branch (/delegates)

### Which version(s) does this affect? (Environment, OS, etc...)
Development branch

**Comment by corbifex** [comment]
fixed
