### ISSUE TITLE
Wrong calculation of "Total Standby Voteweight"

### ISSUE THREAD

**Issue by anonimowy891** [Liskscan/lisk-explorer#3]
### Expected behavior

"Total Standby Voteweight" should show only active standby Voteweight without banned or punished delegates.

### Actual behavior

Looks like is showing now too much in "Total Standby Voteweight", probably includes banned or punished deleates.

### Which version(s) does this affect? (Environment, OS, etc...)

![tempsnip](https://user-images.githubusercontent.com/63446761/156329706-fcf81cd7-065b-4a87-9c50-16e232dc72aa.png)

**Comment by corbifex** [comment]
fixed
